export const colors = {
    LIGHT_GREEN: '#F1F6F1',
    DARK_GREEN: '#548E4E',
    GREENISH_YELLOW: '#C0D73E',
    BACKGROUND_COLOR: '#E5E5E5',
    WHITE: '#FFFFFF',
    GREY: '#F1F1F1',
    GREEN: '#548E4E',
}

export const stringConstants = {
    GREETING_TEXT: 'Good Afternoon,',
    CUSTOMER_NAME: 'Tola',
    WALLET_BALANCE_TEXT: 'Wallet Balance',
    ACCOUNT_NUMBER_TEXT: 'Account Number',
    AIRTIME_TEXT: 'Airtime',
    MTN_TEXT: 'MTN',
    AIRTEL_TEXT: 'Airtel',
    NINE_MOBILE_TEXT: '9Mobile',
    GLO_TEXT: 'glo',
    ELECTRICITY_TEXT: 'Electricity',
    IKEDC_TEXT: 'IKEDC',
    EKEDC_TEXT: 'EKEDC',
    AEDC_TEXT: 'Abuja',
    VIEW_ALL: 'view all',
    DSTV_TEXT: 'DSTV',
    INTERNET_SERVICES_TEXT: 'Internet Services',
    SMILE_TEXT: 'Smile',
    SPECTRANET_TEXT: 'Spectranet',
}