export const colors = {
    LIGHT_GREEN: '#F1F6F1',
    DARK_GREEN: '#548E4E',
    GREENISH_YELLOW: '#C0D73E',
    BACKGROUND_COLOR: '#FAFAFE',
    WHITE: '#FFFFFF',
    BLACK: '#000000',
    GREY: '#F1F1F1',
    GREEN: '#548E4E',
    LIGHT_GREY: '#EAEAEA',
    FEATURE_CONTAINER: '#BDD9BA',
    TRANSACTION_BACKGROUND_COLOR: '#FDFDFD',
    RED: '#FF0000',
    DIVIDER_COLOR: '#C4C4C4',
    PURCHASE_BUTTON_COLOR: '#C0D73E',
    PHONE_NUMBER_INPUT_COLOR: '#9C9C9C'
}

export const stringConstants = {
    GREETING_TEXT: 'Good Afternoon,',
    CUSTOMER_NAME: 'Tola',
    WALLET_BALANCE_TEXT: 'Wallet Balance',
    SEND_MONEY_TEXT: 'Send Money',
    LINK_ACCOUNT_TEXT: 'Link Account',
    PAY_BILLS_TEXT: 'Pay Bills',
    REQUEST_MONEY_TEXT: 'Request Money',
    ACCOUNT_NUMBER_TEXT: 'Account Number',
    AIRTIME_TEXT: 'Airtime',
    MTN_TEXT: 'MTN',
    AIRTEL_TEXT: 'Airtel',
    NINE_MOBILE_TEXT: '9Mobile',
    GLO_TEXT: 'glo',
    ELECTRICITY_TEXT: 'Electricity',
    IKEDC_TEXT: 'IKEDC',
    EKEDC_TEXT: 'EKEDC',
    AEDC_TEXT: 'Abuja',
    VIEW_ALL: 'view all',
    TVBILLS_TEXT: 'TV Bills',
    DSTV_TEXT: 'DSTV',
    INTERNET_SERVICES_TEXT: 'Internet Services',
    SMILE_TEXT: 'Smile',
    SPECTRANET_TEXT: 'Spectranet',
    INPUT_PIN_PROMPT_TEXT: `Enter your transaction PIN to
complete this payment`,
    NETWORK_PROVIDER_TEXT: 'Network Provider',
    CATEGORY_TEXT: 'Category',
    AMOUNT_TEXT: 'Amount',
    PHONE_NUMBER_TEXT: 'Phone Number',
    PAY_WITH_TEXT: 'Pay With',
    BANK_TEXT: 'Bank',
    WALLET_TEXT: '9PSB Wallet',
    BALANCE_TEXT: 'Balance',
    PURCHASE_TEXT: 'Purchase',
    TOPUP_TEXT: 'Mobile Top-up',
    BUNDLE_TEXT: 'Data Bundle',
    CONTACTS_TEXT: 'Contacts',
    RECENT_TRANSACTION_TEXT: 'Recent Transaction',
    DATE: 'Saturday, 11 February 2022',
    CUSTOMER_FULL_NAME_TEXT: 'Sambo Omotola Olanrewaju',
    CREDIT_DESCRIPTION_TEXT: 'Bank transfer from Rasaq Agbala',
    DEBIT_DESCRIPTION_TEXT: 'Transfer to Rasaq Agbala',
    SHOW_MORE_TEXT: 'Show more',
    BILL_PAYMENT_TEXT: 'Bill Payment',
}